package com.trawling.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ObjectID;

@RequiredArgsConstructor
@Getter
public enum HelmTier
{

	BRONZE(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_WOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_WOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_WOOD_IDLE,
		}
	),
	IRON(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_OAK_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_OAK_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_OAK_IDLE,
		}
	),
	STEEL(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_TEAK_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_TEAK_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_TEAK_IDLE,
		}
	),
	MITHRIL(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_MAHOGANY_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_MAHOGANY_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_MAHOGANY_IDLE,
		}
	),
	ADAMANT(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_CAMPHOR_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_CAMPHOR_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_CAMPHOR_IDLE,
		}
	),
	RUNE(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_IRONWOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_IRONWOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_IRONWOOD_IDLE,
		}
	),
	DRAGON(
		new int[]{
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_1X3_ROSEWOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_2X5_ROSEWOOD_IDLE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD_IN_USE,
			ObjectID.SAILING_BOAT_STEERING_KANDARIN_3X8_ROSEWOOD_IDLE,
		}
	),
	;

	private final int[] gameObjectIds;

	public static HelmTier fromGameObjectId(int id)
	{
		for (HelmTier tier : values())
		{
			for (int objectId : tier.getGameObjectIds())
			{
				if (objectId == id)
				{
					return tier;
				}
			}
		}

		return null;
	}

}
